name: orange_ui
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  geolocator: ^14.0.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #_______________ page_navigation & utils ___________________#
  get: ^4.7.3

  #_______________ mvvm structured ___________________#
  stacked: ^3.5.0

  #_______________ local storage ___________________#
  get_storage: ^2.1.1
  path_provider: ^2.1.5

  #_______________ map_integration ___________________#
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocode: ^1.0.3
  flutter_cache_manager: ^3.4.1
  google_maps_cluster_manager_2: ^3.2.0


  #_______________ ui and animation___________________#
  shimmer: ^3.0.0
  lottie: ^3.3.2
  rxdart: ^0.28.0
  custom_marker: ^1.0.0
  flutter_swiper_null_safety: ^1.0.2
  carousel_slider: ^5.1.1
  wakelock_plus: ^1.4.0
  dotted_border: ^3.1.0
  detectable_text_field: ^3.0.2
  smooth_page_indicator: ^2.0.1
  flutter_card_swiper: ^7.2.0
  figma_squircle: ^0.6.3
  calendar_date_picker2: ^2.0.1
  image: ^4.7.2
  csv: ^6.0.0
  expandable_page_view: ^1.2.0
  package_info_plus: ^9.0.0

  #_______________ Networking ___________________#
  http: ^1.6.0

  #_______________ Subscription & In App Purchase ___________________#
  purchases_flutter: ^9.10.3

  #_______________ firebase ___________________#
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  flutter_local_notifications: ^19.5.0
  app_badge_plus: ^1.2.6
  google_mobile_ads: ^7.0.0

  #_______________ sign in  ___________________#
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  #_______________ permission ___________________#
  permission_handler: ^12.0.1

  #_______________ url_launcher ___________________#
  url_launcher: ^6.3.2

  #____________________ date_format: _________________#
  intl: ^0.20.2

  #_______________ video and image_____________#
  image_picker: ^1.2.1
  video_player: ^2.10.1
  cached_network_image: ^3.4.1
  video_compress: ^3.1.4

  #_____________live streaming_________________#
  agora_rtc_engine: ^6.5.3

  #_____________ webView _________________#
  webview_flutter_plus: ^0.4.19

  #_____________ Share _________________#
  share_plus: ^12.0.1
  app_links: ^7.0.0

  collection: ^1.19.1

  ### ðŸ”Œ Custom Plugins
  retrytech_plugin:
    git:
      url: https://gitlab.com/jeelkhokhariya59/retrytech_plugin.git
      ref: master



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/csv/
    - lib/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy_reguler.ttf

    - family: gilroy_bold
      fonts:
        - asset: assets/fonts/gilroy_bold.ttf

    - family: gilroy_extra_bold
      fonts:
        - asset: assets/fonts/gilroy_extra_bold.otf

    - family: gilroy_heavy
      fonts:
        - asset: assets/fonts/gilroy_heavy.ttf

    - family: gilroy_light
      fonts:
        - asset: assets/fonts/gilroy_light.otf

    - family: gilroy_medium
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf

    - family: gilroy_semibold
      fonts:
        - asset: assets/fonts/gilroy_semibold.ttf

    - family: gilroy_heavyItalic
      fonts:
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
